import './globals.css'
import React from 'react';
import ReactDOM from "react-dom";
import Page from "./page";  

ReactDOM.render(
  // Our main React application component, which we've imported from another file
  <Page />,
  // Gets rendered to the <div> we defined in our Django template using the shared id
  document.getElementById('react-root')
);

// export const metadata = {
//   title: 'Pyxis Habits',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
