# Generated by Django 4.2 on 2023-05-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_color_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='color_theme',
            field=models.CharField(choices=[('D', 'dark'), ('L', 'light'), ('C', 'colorblind')], default='L', max_length=1),
        ),
    ]
